# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end 	
  
  config.vm.network "forwarded_port", guest: 8545, host: 8545
  config.vm.network "private_network", ip: "192.168.201.55"

  config.vm.synced_folder "/GitHub/onechain-back/eth/", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision :shell, inline: <<-SHELL
	sudo yum update -y
	sudo yum -y install wget
	
	# Install golang, git, unzip, dos2unix
 	sudo yum install -y g++ golang git unzip dos2unix

    # Install java
	sudo yum install -y java-1.8.0-openjdk
       
    # Install gradle
    wget --progress=dot:giga https://services.gradle.org/distributions/gradle-4.2.1-bin.zip
	sudo unzip -d /opt/gradle gradle-4.2.1-bin.zip
    
    # Install node.js
    curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash - 
	sudo yum install -y nodejs
	
	# Install various etherium npm tools
    sudo npm install -g sync-exec@0.6.2
    sudo npm install -g solc@0.8.13
    sudo npm install -g web3@1.7.3
    sudo npm install -g truffle@4.1.14
    sudo npm install -g ganache@7.1.0
    sudo npm install -g mocha@6.2.3
	sudo npm install -g babel-runtime@6.26.0

    sudo printf "\n192.168.201.55\tbackchain-vagrant.onenetwork.com\n" >> /etc/hosts
    
    printf ". ~/.bashrc\ncd /vagrant\n. .env.sh\n" >> /home/vagrant/.bash_profile
    mkdir /home/vagrant/log
     
    sudo chown -R vagrant /home/vagrant

	cd /vagrant
    sudo su - vagrant -c 'bk start'
	
    printf "\n\n=== Provisioning Complete ===\n"
  SHELL
end